# Список возможных нештатных ситуаций

* Падение таски. Падает только одна таска, остальные продолжают работать.
    - Непойманное исключение (`ModuleOperationException`).
    - Segmentation fault в С++ коде (`ModuleOperationCrash`).
* Превышение по памяти в одной из тасок. 
  YT рестартит джобу, но срабатывает защита в `yt_module_executor` от рестарта такой-же таски. 
  Падает только одна таска, остальные продолжают работать.
* YT отменил операцию (например пользователь нажал abort через GUI YT) (`YtOperationFailedError`). 
  Отменяются запущенные таски, после чего
  они рестартятся внутри новой ванила операции. Те таски, которые успели выполниться, не рестартятся.
* YT отменил одну джобу. Таска ретраится в другой ванила операции. Остальные таски продолжают работу.
* Упал module_executor, который должен регулярно посылать уведомления о том, что таска жива.

# Возможные действия в случае нештатных ситуаций

* Если таска выбрасывает исключение, то имя исключения проверяется по списку в 
  `maps.garden.libs_server.pymod.handler._RETRIABLE_ERROR_CLASSNAMES`. 
  Если имя исключения есть в списке, то таска рестартится,
  если нет - таска считается зафейлившийся и ошибка отдаётся дальше в `RequestHandler`.
* Если таска крэшится, то таска считается зафейлившийся и ошибка отдаётся дальше в `RequestHandler`.
* Если YT прибил джобу из-за того, что таска потребовала памяти больше лимита (`memory limit exceeded`),
  то таска считается зафейлившийся и ошибка отдаётся дальше в `RequestHandler`.
* Если YT прибил джобу по любой другой причине, то таска рестартится.
* Если упал тул `yt_module_executor`, то таска рестартится.
